server:
    port: 8085
    servlet:
        context-path: /notification-service/api

spring:
    application:
        name: notification-service
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
        driver-class-name: org.h2.Driver
        username: sa
        password:
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: true
                format_sql: true

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: alpha
        defaultModelsExpandDepth: 1

logging:
    level:
        com.taxi.rideUp: DEBUG
        org.hibernate.type: DEBUG
